<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTpvojti\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTpvojti/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTpvojti.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTpvojti\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTpvojti\appProdProjectContainer([
    'container.build_hash' => 'Tpvojti',
    'container.build_id' => 'cdeefb85',
    'container.build_time' => 1672130403,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTpvojti');
